require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Webhook deliveries run as background jobs, and the whole point is that the
  # endpoint answers GitHub before the work starts. :async would drop queued
  # jobs on restart and hide that the production path is durable, so
  # development runs the same Solid Queue as production — in the `jobs`
  # compose service (see docker-compose.yml and docs/webhooks.md).
  config.active_job.queue_adapter = :solid_queue

  # A tunnel gives the dev server a public hostname, which Rails' host
  # authorization would otherwise reject with "Blocked hosts". Nothing is
  # allowed that PRISM_PUBLIC_URL doesn't name.
  #
  # Webhooks::PublicUrl parses the same variable everywhere else, but an
  # environment file runs before autoloading, so this one spot has to do it by
  # hand.
  tunnel_host =
    begin
      ENV["PRISM_PUBLIC_URL"].presence && URI.parse(ENV["PRISM_PUBLIC_URL"]).host
    rescue URI::InvalidURIError
      nil
    end
  config.hosts << tunnel_host if tunnel_host.present?

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
